---
functional:
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность настраивать параметры игры при создании
  - Пользователь должен иметь возможность присоединиться к созданной другим пользователем игре
  - Пользователь должен иметь возможность достигать целей игры
  - Пользователь должен иметь возможность завершить игру по истечению времени или по достижению целей игры
  - Пользователь должен иметь возможность завершить игру без достижения цели игры или истечения времени на игру
  - Пользователь должен иметь возможность общаться в чате
  - Пользователь должен иметь возможность участвовать в рейтинговой системе
non-functional:
  - Дизайн сайта должен быть удобен для использования на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность повторно подключиться к игре при потере соединения до завершения игры
  - Пользователь должен иметь возможность оставить обратную связь об ошибках в задачах
